sudo: required

language: go

go:
  - master

addons:
  apt:
    packages:
      - docker-ce

script:
  - chmod +x test.sh
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CGO_ENABLED=0 go build

deploy:
  skip_cleanup: true
  provider: script
  script: sh build_docker.sh
  on:
    branch: master