version: '3.6'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: set_your_database_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  bot:
    image: trigun117/tproxy-bot
    restart: always
    environment:
      TOKEN: set_your_bot_token
      TABLE: create
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: set_your_database_password
      DBNAME: postgres
      SSLMODE: disable
      LINK: site_link
      MTL: mtproto_link
      URL: site_json_url
      PASS: site_json_password
      FI: site_json_field

volumes:
  pgdata: {}